export const ratingOptions = [
    { value: null, label: 'No Rating' },
    { value: 'FIVE_PLUS', label: '5+' },
    { value: 'THIRTEEN_PLUS', label: '13+' },
    { value: 'FIFTEEN_PLUS', label: '15+' },
    { value: 'EIGHTEEN_PLUS', label: '18+' },
    { value: 'NR', label: 'NR' },
    { value: 'G', label: 'G' },
    { value: 'PG', label: 'PG' },
    { value: 'PG_13', label: 'PG-13' },
    { value: 'R', label: 'R' },
    { value: 'NC_17', label: 'NC-17' },
    { value: 'TV_Y', label: 'TV-Y' },
    { value: 'TV_Y7', label: 'TV-Y7' },
    { value: 'TV_Y7_FV', label: 'TV-Y7-FV' },
    { value: 'TV_G', label: 'TV-G' },
    { value: 'TV_14', label: 'TV-14' },
    { value: 'TV_MA', label: 'TV-MA' },
    { value: 'TV_PG', label: 'TV-PG' },
    { value: 'TV_PG_L', label: 'TV-PG-L' },
    { value: 'TV_14_L', label: 'TV-14-L' },
    { value: 'TV_14_D', label: 'TV-14-D' },
    { value: 'TV_14_D_L', label: 'TV-14-D-L' },
    { value: 'A', label: 'A' },
    { value: 'A_EIGHTEEN_PLUS', label: 'A 18+' },
    { value: 'UA', label: 'UA' },
    { value: 'U', label: 'U' },
    { value: 'U_All_Ages', label: 'U All Ages' },
    { value: 'UA_SEVEN_PLUS', label: 'U/A 7+' },
    { value: 'UA_THIRTEEN_PLUS', label: 'U/A 13+' },
    { value: 'UA_SIXTEEN_PLUS', label: 'U/A 16+' },
    { value: 'NA', label: 'NA' },
    { value: 'S', label: 'S' },
  ];